config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users
  resources :books, only: [:new, :index, :show, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :create]

  get "/home/about" => "homes#about", as: "about"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :profile_image

  belongs_to :user

  validates :title, presence:true
  validates :body, length: { in:1..200 }

  

  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'profile_image.jpeg', content_type: 'image/jpeg')
   end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/models/user.rb
class User < ApplicationRecord

  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books

  has_one_attached :profile_image

  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'profile_image.jpeg', content_type: 'image/jpeg')
   end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :name, length: { in:2..20 }, uniqueness: true
  validates :introduction, length: { maximum:50 }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)

  end



  def after_sign_out_path_for(resource)
    
    root_path

  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end



  def index
   @book = Book.new
   @books = Book.all
   @book.user_id = current_user.id
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
     flash[:notice] = "You have created book successfully."
     redirect_to book_path(@book)
    else
     @books = Book.all
     render :index
    end
  end

  def show
   @book = Book.new
   @books = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    book = Book.find(params[:id])
    unless book.user.id == current_user.id
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
     flash[:notice] = "You have updated book successfully."
     redirect_to book_path
    else
     render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:title, :body, :image)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
   
  end
  
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
   @book = Book.new
   @book.user_id = current_user.id
   @users = User.all
   @user = current_user
  end

  def show
   @book = Book.new
   @user = User.find(params[:id])
   @book.user_id = @user.id
   @books = @user.books
  end

  def edit
    user = User.find(params[:id])
     unless user.id == current_user.id
      redirect_to user_path(current_user.id)
     end
   @user = User.find(params[:id])
  end

   def create
    @user = User.new(user_params)
    @user = current_user.id
    if @user.save
     flash[:notice] = "Welcome! You have signed up successfully."
     redirect_to users_path(current_user.id)
    else
      flash[:notice] =  "error"
      render :new
    end
   end

   def update
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to books_path
    end
    @user = User.find(params[:id])
    if @user.update(user_params)
     flash[:notice] = "You have updated user successfully."
     redirect_to user_path(@user.id)
    else
      flash[:notice] =  "error"
      render :edit
    end
   end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/show_helper.rb
module ShowHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
    <h2>User info</h2>
     <% if current_user.profile_image.attached? %>
      <%= image_tag book.user.get_profile_image(100,100) %>
     <% else %>
      <%= image_tag 'no_image', size: "105x105" %>
     <% end %>
     <table class="table">
      <tr>
       <th><p>name</p></th>
       <td><%= book.user.name %></td>
      </tr>
      <tr>
       <th><p>introduction</p></th>
       <td><%= book.user.introduction %></td>
      </tr>
     </table>
     <%= link_to edit_user_path(book.user.id), class:"btn btn-outline-secondary btn-block" do %>
      <i class="fa-solid fa-user-gear"></i>
     <% end %>



    <h2>New book</h2>
     <%= form_with model: @book do |f| %>
     <p>Title</p>
      <%= f.text_field :title %>
     <p>Opinion</p>
      <%= f.text_area :body %>
     <%= f.submit 'Create Book', class:"btn btn-success" %>
     <% end %>
  

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<h2>Editing Book</h2>
 <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <p>Title</p>
   <%= f.text_field :title %>
  <p>Opinion<p>
   <%= f.text_area :body %>
  <p><%= f.submit "Update Book", class:"btn btn-success" %></p>
 <% end %>

<%= link_to "Show", book_path(@book.id) %>
<%= link_to "Back", books_path %>

app/views/books/index.html.erb
 <% if @book.errors.any? %>
  <%= @book.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row">
   <div class="col-md-3">
   <%= render 'books/list', book:@book %>
   </div>
   
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
    <table>
     <tr>
      <th></th>
      <th><p>Title</p></th>
      <th><p>Opinion</p></th>
     </tr>
     <tr>
      <% @books.each do |book| %>
      <td>
       <% if current_user.profile_image.attached? %>
         <%= link_to user_path(book.user_id) do %>
          <%= image_tag @book.user.get_profile_image(105,105) %>
         <% end %>
       <% else %>
         <%= link_to user_path(book.user_id) do %>
          <%= image_tag 'no_image', size: "105x105" %>
         <% end %>
       <% end %>
      </td>
      <td>
       <span><%= link_to book.title, book_path(book.id) %></span>
      </td>
      <td>
       <span><%= book.body %></span>
      </td>
     </tr>
      <% end %>
    </table>
  </div>
 </div>
</div>

app/views/books/show.html.erb
<div class="container">

 <div class="row">
  <div class="col-md-3">
   <%= render 'books/list', book:@books %>
  </div>
  
  <div class="col-md-8 offset-md-1">
   <h2>Book detail</h2>
   <table class= "table">
    <tr>
     <td>
      <% if current_user.profile_image.attached? %>
       <%= link_to user_path(@books.user_id) do %>
        <%= image_tag @books.user.get_profile_image(105,105) %>
       <% end %>
      <% else %>
       <%= link_to user_path(@books.user_id) do %>
        <%= image_tag 'no_image', size: "105x105" %>
       <% end %>
      <% end %>
      <br><%= link_to @books.user.name, user_path(@books.user_id) %>
     </td>
     <td><p><%= @books.title %></p></td>
     <td><p><%= @books.body %></p></td>
     <td><% if @books.user == current_user %>
        <%= link_to "Edit", edit_book_path, class:"btn btn-success" %>
       <% end %>
     </td>
     <td><% if @books.user == current_user %>
       <%= link_to "Destroy", book_path, method: :delete, class:"btn btn-danger" %>
      <% end %>
     </td>
    </tr>
   </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to <i class="fa-solid fa-book"></i>Bookers!</h1>

app/views/homes/top.html.erb
<h1>welcome to <i class="fa-solid fa-book"></i>Bookers!!</h1>
<p>In <i class="fa-solid fa-book"></i>Bookers,</p>
<p>you can share and exchange your opinions,inpressions, and emotions</p>
<p>about various books!</p>

<%= link_to "Log in", new_user_session_path, class:"btn btn-primary" %>
<%= link_to "Sign up", new_user_registration_path, class:"btn btn-success" %>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://kit.fontawesome.com/d9417e9e89.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body class="d-flex flex-column vh-100">
    <header class="bg-dark text-white pt-5 pb-4">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
         <a class="navar-brand" href="/">
          <span>Bookers</span>
          </a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

    <% if user_signed_in? %>

     <li>
       <%= link_to user_path(current_user.id) do %>
       <i class="fa-solid fa-house"></i>Home
       <% end %>
     </li>
     <li>
       <%= link_to users_path do %>
       <i class="fa-solid fa-users"></i>Users
       <% end %>
     </li>
     <li>
       <%= link_to  books_path do %>
       <i class="fa-solid fa-book-open"></i>Books
       <% end %>
     </li>
     <li>
       <%= link_to  destroy_user_session_path, method: :delete do %>
       <i class="fa-solid fa-right-from-bracket"></i>Log out
       <% end %>
     </li>
    <% else %>

      <li>
       <%= link_to root_path do %>
       <i class="fa-solid fa-house"></i>Home
       <% end %>
      </li>
      <li>
       <%= link_to  about_path do %>
       <i class="fa-solid fa-link"></i>About
       <% end %>
      </li>
      <li>
       <%= link_to  new_user_registration_path do %>
       <i class="fa-solid fa-user-plus"></i>Sign up
       <% end %>
     </li>
      <li>
       <%= link_to  new_user_session_path do %>
       <i class="fa-solid fa-right-to-bracket"></i>Log in
       <% end %>
     </li>
    <% end %>
    </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <p class="notice"><%= notice %></p>
    <%= yield %>
    </main>

    <footer class="bg-white text-black pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">

      <p>CopyRight Infratop.inc</p>
      </div>
      </div>
    </footer>

  </body>
</html>

app/views/users/edit.html.erb
<h2>Users info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>error prohibited this obj from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
 <p>Name</p>
 <%= f.text_field :name %>
 <p>Image</p>
 <%= f.file_field :profile_image, accept: "image/*" %>
 <p>Introduction</p>
 <%= f.text_area :introduction %>
 <p><%= f.submit "Update User", class:"btn btn-secondary" %></p>
<% end %>

app/views/users/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <%= render 'books/list', book:@book %>
  </div>
   
  <div class="col-md-8 offset-md-1">
    <h2>Users</h2>
     <table class="table">
      <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
      </tr>
      <tr>
       <% @users.each do |user| %>
       <td>
        <% if current_user.profile_image.attached? %>
         <%= link_to user_path(@book.user_id) do %>
          <%= image_tag @book.user.get_profile_image(105,105) %>
         <% end %>
        <% else %>
         <%= link_to user_path(@book.user_id) do %>
          <%= image_tag 'no_image', size:"105x105" %>
         <% end %>
        <% end %>
       </td>
       <td>
        <span><%= user.name %></span>
       </td>
       <td>
        <span>
         <%= link_to "Show", user_path(user.id) %>
        </span>
       </td>

      </tr>
      <% end %>
     </table>

  </div>
 </div>
</div>

app/views/users/show.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-3">
   <%= render 'books/list', book:@book %>
  </div>
  
  <div class="col-md-8 offset-md-1">
   <h2>Books</h2>
     <table class= "table" >
      <tr>
       <th></th>
       <th><p>Title</p></th>
       <th><p>Opinion</p></th>
      </tr>
      <tr>
      <% @books.each do |book| %>
       <td>
        <% if current_user.profile_image.attached? %>
         <%= link_to user_path(book.user_id) do %>
          <%= image_tag book.user.get_profile_image(105,105) %>
         <% end %>
        <% else %>
         <%= link_to user_path(book.user_id) do %>
          <%= image_tag 'no_image', size:"105x105" %>
         <% end %>
        <% end %>
       </td>
       <td>
        <span>
         <%= link_to book.title, book_path(book.id)  %>
        </span>
       </td>
       <td>
        <span><%= book.body %></span>
       </td>
      </tr>
      <% end %>
     </table>


  </div>
 </div>
</div>